server:
  port: '8081'
#  ssl:
#    key-store: classpath:cert.p12
#    key-store-password: Mkx6d1@667
#    key-store-type: PKCS12
#    key-alias: mykey
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dictionary
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: Mkx6d1@667
  application:
    name: AUTHENTICATION-SERVICE
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/