server:
  port: 8443
  ssl:
    key-store: classpath:cert.p12
    key-store-password: Mkx6d1@667
    key-store-type: PKCS12
    key-alias: mykey
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: authentication-service
          uri: http://localhost:8081/
          predicates:
            - Path= /auth-service/**
        - id: history-service
          uri: http://localhost:8082/
          predicates:
            - Path= /history-service/**