server:
  ssl:
    keyAlias: history
    key-store-password: Mkx6d1@667
    key-store: classpath:keystore.p12
    keyStoreType: PKCS12
  port: 2096
spring:
  data:
    mongodb:
      authentication-database: admin
      username: mongo
      database: history
      password: Mkx6d1@667
      port: '27017'
      host: localhost
